server:
  port: 8081
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group