server:
  port: 8081
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
  datasource:
    url: jdbc:h2:mem:testdb