server:
  port: 8081
spring:
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers: localhost:29092,localhost:39092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
topics:
  retry: "library-events.RETRY"
  dlt: "library-events.DLT"