spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer