spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092,localhost:39092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: library-events
    properties:
      acks: all
      retries: 10